import { jsPDF } from 'jspdf';
import {
  BUDGET_CATEGORY_LABELS,
  buildProgrammeFormFileName,
  calculateBudgetTotals,
  formatCurrency,
} from './programmeFormConstants';

const SDG_LABELS = {
  1: 'NO POVERTY',
  2: 'ZERO HUNGER',
  3: 'GOOD HEALTH AND WELL-BEING',
  4: 'QUALITY EDUCATION',
  5: 'GENDER EQUALITY',
  6: 'CLEAN WATER AND SANITATION',
  7: 'AFFORDABLE AND CLEAN ENERGY',
  8: 'DECENT WORK AND ECONOMIC GROWTH',
  9: 'INDUSTRY, INNOVATION AND INFRASTRUCTURE',
  10: 'REDUCED INEQUALITIES',
  11: 'SUSTAINABLE CITIES AND COMMUNITIES',
  12: 'RESPONSIBLE CONSUMPTION AND PRODUCTION',
  13: 'CLIMATE ACTION',
  14: 'LIFE BELOW WATER',
  15: 'LIFE ON LAND',
  16: 'PEACE, JUSTICE AND STRONG INSTITUTIONS',
  17: 'PARTNERSHIPS FOR THE GOALS',
};

const COLORS = {
  primary: [30, 64, 175],
  text: [15, 23, 42],
  muted: [71, 85, 105],
  border: [203, 213, 225],
  sectionBg: [239, 246, 255],
};

const FOOTER_RESERVE = 24;
const SECTION_GAP = 10;
const LINE_HEIGHT = 5;
const TABLE_LINE_HEIGHT = 4.8;
const TEXT_PADDING_TOP = 7;

const loadImageMeta = (url) =>
  new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.naturalWidth || img.width;
      canvas.height = img.naturalHeight || img.height;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0);
      resolve({
        dataUrl: canvas.toDataURL('image/jpeg', 0.92),
        width: canvas.width,
        height: canvas.height,
      });
    };
    img.onerror = () => reject(new Error('Failed to load poster image.'));
    img.src = url;
  });

const fitImageBox = (naturalWidth, naturalHeight, maxWidth, maxHeight) => {
  const ratio = naturalWidth / naturalHeight;
  let width = maxWidth;
  let height = width / ratio;
  if (height > maxHeight) {
    height = maxHeight;
    width = height * ratio;
  }
  return {
    width,
    height,
    xOffset: (maxWidth - width) / 2,
    yOffset: (maxHeight - height) / 2,
  };
};

const ensureSpace = (doc, y, needed, margin) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - FOOTER_RESERVE) {
    doc.addPage();
    return margin + 10;
  }
  return y;
};

const drawPageFooter = (doc, margin) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const page = doc.internal.getCurrentPageInfo().pageNumber;
  const total = doc.internal.getNumberOfPages();

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text('Generated by CampusLink+ · Universiti Malaysia Terengganu', margin, pageHeight - 8);
  doc.text(`Page ${page} of ${total}`, pageWidth - margin, pageHeight - 8, { align: 'right' });
};

const drawDocumentHeader = (doc, margin) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 16;

  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.primary);
  doc.text('UNIVERSITI MALAYSIA TERENGGANU', pageWidth / 2, y, { align: 'center' });
  y += 7;

  doc.setFontSize(11);
  doc.setTextColor(...COLORS.text);
  doc.text('BORANG PERMOHONAN PROGRAM KOKURIKULUM / SUKAN', pageWidth / 2, y, { align: 'center' });
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  doc.text('MyStar Programme Proposal Form (CampusLink+)', pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.4);
  doc.line(margin, y, pageWidth - margin, y);
  return y + SECTION_GAP;
};

const drawSectionTitle = (doc, title, y, margin, maxWidth) => {
  y = ensureSpace(doc, y, 16, margin);
  doc.setFillColor(...COLORS.sectionBg);
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.4);
  doc.rect(margin, y, maxWidth, 9, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.primary);
  doc.text(title, margin + 4, y + 6.2);
  return y + 12;
};

const drawFieldRow = (doc, label, value, y, margin, maxWidth, labelWidth = 54) => {
  const valueX = margin + labelWidth;
  const valueWidth = maxWidth - labelWidth;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  const labelLines = doc.splitTextToSize(label, labelWidth - 6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const valueLines = doc.splitTextToSize(String(value || '—'), valueWidth - 6);
  const lineCount = Math.max(labelLines.length, valueLines.length);
  const rowHeight = Math.max(12, lineCount * LINE_HEIGHT + 8);

  y = ensureSpace(doc, y, rowHeight + 2, margin);

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.25);
  doc.rect(margin, y, maxWidth, rowHeight);
  doc.line(valueX, y, valueX, y + rowHeight);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.muted);
  labelLines.forEach((line, index) => {
    doc.text(line, margin + 3, y + TEXT_PADDING_TOP + index * LINE_HEIGHT);
  });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.text);
  valueLines.forEach((line, index) => {
    doc.text(line, valueX + 3, y + TEXT_PADDING_TOP + index * LINE_HEIGHT);
  });

  return y + rowHeight;
};

const drawMultilineBlock = (doc, label, value, y, margin, maxWidth) => {
  y += 4;
  const contentLines = doc.splitTextToSize(String(value || '—'), maxWidth - 10);
  const contentHeight = Math.max(14, contentLines.length * LINE_HEIGHT + 10);
  const totalHeight = 9 + contentHeight;

  y = ensureSpace(doc, y, totalHeight + 4, margin);

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.25);
  doc.rect(margin, y, maxWidth, totalHeight);
  doc.setFillColor(...COLORS.sectionBg);
  doc.rect(margin, y, maxWidth, 9, 'F');
  doc.line(margin, y + 9, margin + maxWidth, y + 9);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.primary);
  doc.text(label, margin + 3, y + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.text);
  doc.text(contentLines, margin + 4, y + 15);

  return y + totalHeight + 4;
};

const drawDataTable = (doc, headers, colWidths, rows, y, margin, maxWidth) => {
  let x = margin;

  y = ensureSpace(doc, y, 10, margin);
  doc.setFillColor(...COLORS.sectionBg);
  doc.setDrawColor(...COLORS.border);
  doc.rect(margin, y, maxWidth, 8, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.primary);
  headers.forEach((header, index) => {
    doc.text(header, x + 2, y + 5.5);
    x += colWidths[index];
  });
  y += 8;

  rows.forEach((row) => {
    const cellLines = row.map((cell, index) =>
      doc.splitTextToSize(String(cell || '—'), colWidths[index] - 4)
    );
    const lineCount = Math.max(...cellLines.map((lines) => lines.length));
    const rowHeight = Math.max(10, lineCount * TABLE_LINE_HEIGHT + 8);
    y = ensureSpace(doc, y, rowHeight + 2, margin);
    x = margin;
    row.forEach((cell, index) => {
      doc.setDrawColor(...COLORS.border);
      doc.rect(x, y, colWidths[index], rowHeight);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.text);
      cellLines[index].forEach((line, lineIndex) => {
        doc.text(line, x + 2, y + TEXT_PADDING_TOP + lineIndex * TABLE_LINE_HEIGHT);
      });
      x += colWidths[index];
    });
    y += rowHeight;
  });

  return y + SECTION_GAP;
};

export const generateProgrammeFormPdf = async (
  formData,
  organizerName = '',
  meritPreview = null,
  options = { download: true }
) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const margin = 16;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = drawDocumentHeader(doc, margin);

  if (formData.posterPreview) {
    try {
      const poster = await loadImageMeta(formData.posterPreview);
      const posterBoxHeight = 110;
      const fit = fitImageBox(poster.width, poster.height, maxWidth - 12, posterBoxHeight - 12);

      y = ensureSpace(doc, y, posterBoxHeight + 20, margin);
      y = drawSectionTitle(doc, 'PROGRAMME POSTER', y, margin, maxWidth);

      doc.setDrawColor(...COLORS.border);
      doc.setLineWidth(0.4);
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, y, maxWidth, posterBoxHeight, 'FD');

      doc.addImage(
        poster.dataUrl,
        'JPEG',
        margin + 6 + fit.xOffset,
        y + 6 + fit.yOffset,
        fit.width,
        fit.height
      );
      y += posterBoxHeight + SECTION_GAP;
    } catch {
      // Poster is optional.
    }
  }

  y = drawSectionTitle(doc, 'A. PROGRAMME INFORMATION', y, margin, maxWidth);
  y = drawFieldRow(doc, 'Programme Title', formData.title, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Category', formData.category, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Programme Level', formData.level, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Programme Type', formData.type, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Organizer Club', formData.organizerClub, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Organizer Name', organizerName, y, margin, maxWidth);
  y = drawMultilineBlock(doc, 'Description', formData.description, y, margin, maxWidth);
  y = drawMultilineBlock(doc, 'Objectives', formData.objectives, y, margin, maxWidth);
  y = drawMultilineBlock(doc, 'Expected Outcomes', formData.outcomes, y, margin, maxWidth);

  y += SECTION_GAP;
  y = drawSectionTitle(doc, 'B. SCHEDULE, VENUE & REGISTRATION', y, margin, maxWidth);
  y = drawFieldRow(
    doc,
    'Start',
    `${formData.startDate || '—'}${formData.startTime ? ` · ${formData.startTime}` : ''}`,
    y,
    margin,
    maxWidth
  );
  y = drawFieldRow(
    doc,
    'End',
    `${formData.endDate || '—'}${formData.endTime ? ` · ${formData.endTime}` : ''}`,
    y,
    margin,
    maxWidth
  );
  y = drawFieldRow(doc, 'Registration Open', formData.registrationOpenDate, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Registration Close', formData.registrationCloseDate, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Venue', formData.venue, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Google Maps', formData.googleMapsLocation, y, margin, maxWidth);
  y = drawFieldRow(doc, 'Max Participants', formData.maxParticipants, y, margin, maxWidth);
  y = drawFieldRow(
    doc,
    'Participant Estimation',
    `Students: ${formData.expectedStudentParticipants || '0'} | Staff: ${formData.expectedStaffParticipants || '0'} | External: ${formData.expectedExternalParticipants || '0'}`,
    y,
    margin,
    maxWidth
  );

  y += SECTION_GAP;
  y = drawSectionTitle(doc, 'C. BUDGET SUMMARY', y, margin, maxWidth);
  const budgetTotals = calculateBudgetTotals(formData.budgetLines || []);
  const budgetRows = (formData.budgetLines || [])
    .filter((line) => Number(line.amount) > 0)
    .map((line) => [
      line.lineType === 'INCOME' ? 'Income' : 'Expense',
      BUDGET_CATEGORY_LABELS[line.category] || line.category,
      formatCurrency(line.amount),
    ]);
  if (budgetRows.length) {
    const budgetColWidths = [maxWidth * 0.18, maxWidth * 0.52, maxWidth * 0.30];
    y = drawDataTable(doc, ['Type', 'Category', 'Amount (RM)'], budgetColWidths, budgetRows, y, margin, maxWidth);
  }
  y = drawFieldRow(doc, 'Total Income', formatCurrency(budgetTotals.totalIncome), y, margin, maxWidth);
  y = drawFieldRow(doc, 'Total Expense', formatCurrency(budgetTotals.totalExpense), y, margin, maxWidth);
  y = drawFieldRow(doc, 'Budget Balance', formatCurrency(budgetTotals.balance), y, margin, maxWidth);

  y += SECTION_GAP;
  y = drawSectionTitle(doc, 'D. PROGRAMME TENTATIVE', y, margin, maxWidth);
  const tentativeRows = (formData.tentativeSchedule || [])
    .filter((row) => row.timeSlot?.trim() || row.activity?.trim() || row.personInCharge?.trim())
    .map((row) => [row.timeSlot || '—', row.activity || '—', row.personInCharge || '—']);
  if (tentativeRows.length) {
    const tentativeColWidths = [maxWidth * 0.22, maxWidth * 0.48, maxWidth * 0.30];
    y = drawDataTable(
      doc,
      ['Time', 'Activity', 'Person in Charge'],
      tentativeColWidths,
      tentativeRows,
      y,
      margin,
      maxWidth
    );
  } else {
    y = drawFieldRow(doc, 'Tentative Schedule', 'No schedule rows provided.', y, margin, maxWidth);
    y += SECTION_GAP;
  }

  y = drawSectionTitle(doc, 'E. SPEAKER INFORMATION', y, margin, maxWidth);
  const speakerRows = (formData.speakers || [])
    .filter((speaker) => speaker.speakerName?.trim())
    .map((speaker) => [
      speaker.speakerName,
      speaker.position || '—',
      speaker.organization || '—',
      speaker.email || '—',
      speaker.phone || '—',
      speaker.cvFileName || speaker.cvPath ? 'Attached' : '—',
    ]);
  if (speakerRows.length) {
    const speakerColWidths = [
      maxWidth * 0.18,
      maxWidth * 0.14,
      maxWidth * 0.18,
      maxWidth * 0.22,
      maxWidth * 0.14,
      maxWidth * 0.14,
    ];
    y = drawDataTable(
      doc,
      ['Name', 'Position', 'Organization', 'Email', 'Phone', 'CV'],
      speakerColWidths,
      speakerRows,
      y,
      margin,
      maxWidth
    );
  } else {
    y = drawFieldRow(doc, 'Speakers', 'No speakers listed.', y, margin, maxWidth);
    y += SECTION_GAP;
  }

  y += SECTION_GAP;
  y = drawSectionTitle(doc, 'F. PROGRAMME COMMITTEE (MYSTAR)', y, margin, maxWidth);

  const committeeRows = [];
  const director = formData.committee?.director;
  if (director?.matric || director?.name) {
    committeeRows.push([
      'Programme Director',
      director.name || '—',
      director.matric || '—',
      director.faculty || '—',
    ]);
  }
  (formData.committee?.mtMembers || []).forEach((member, index) => {
    if (!member.matric) return;
    committeeRows.push([
      `MT Programme ${index + 1}`,
      member.name || '—',
      member.matric || '—',
      `${member.faculty || '—'}${member.position ? ` · ${member.position}` : ''}`,
    ]);
  });
  (formData.committee?.ajkMembers || []).forEach((member, index) => {
    if (!member.matric) return;
    committeeRows.push([
      `AJK Programme ${index + 1}`,
      member.name || '—',
      member.matric || '—',
      `${member.faculty || '—'}${member.role ? ` · ${member.role}` : ''}`,
    ]);
  });
  (formData.committee?.specialContributions || []).forEach((member, index) => {
    if (!member.matric) return;
    committeeRows.push([
      `Special Contribution ${index + 1}`,
      member.name || '—',
      member.matric || '—',
      `${member.faculty || '—'} · ${member.contributionDescription || '—'}`,
    ]);
  });

  const committeeColWidths = [maxWidth * 0.24, maxWidth * 0.26, maxWidth * 0.18, maxWidth * 0.32];
  if (committeeRows.length) {
    y = drawDataTable(
      doc,
      ['Role', 'Name', 'Matric', 'Faculty / Position'],
      committeeColWidths,
      committeeRows,
      y,
      margin,
      maxWidth
    );
  } else {
    y = drawFieldRow(doc, 'Committee', 'No committee members listed.', y, margin, maxWidth);
    y += SECTION_GAP;
  }

  y = drawSectionTitle(doc, 'G. MYSTAR MERIT SUMMARY', y, margin, maxWidth);
  const meritRows = [];
  if (meritPreview?.rules) {
    meritRows.push([
      'Merit Rules',
      `Director ${meritPreview.rules.DIRECTOR ?? '—'} | MT ${meritPreview.rules.MT ?? '—'} | AJK ${meritPreview.rules.AJK ?? '—'} | Special ${meritPreview.rules.SPECIAL_CONTRIBUTION ?? '—'}`,
    ]);
  }
  (meritPreview?.breakdown || []).forEach((item) => {
    meritRows.push([
      item.positionLabel || item.committeeRole || 'Committee',
      `${item.matricNumber || '—'} — ${item.meritPoints ?? 0} points`,
    ]);
  });
  meritRows.push(['Total Committee Merit', `${meritPreview?.totalMerit ?? 0} points`]);

  const meritColWidths = [maxWidth * 0.42, maxWidth * 0.58];
  y = drawDataTable(doc, ['Position / Item', 'Matric / Points'], meritColWidths, meritRows, y, margin, maxWidth);

  y = drawSectionTitle(doc, 'H. SUSTAINABLE DEVELOPMENT GOALS (SDG)', y, margin, maxWidth);
  y = ensureSpace(doc, y, 14, margin);
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text('(Sila tanda (/) di kotak SDG yang berkenaan)', margin, y);
  y += 6;
  doc.text('*Minta pandangan penasihat kelab untuk menandakan SDG yang terlibat.', margin, y);
  y += 8;

  const selectedSdgs = new Set(formData.sdgs || []);
  const leftColumn = [1, 2, 3, 4, 5, 6, 7, 8, 9];
  const rightColumn = [10, 11, 12, 13, 14, 15, 16, 17];
  const colWidth = (maxWidth - 8) / 2;
  const sdgLineHeight = 6;

  doc.setFontSize(8);
  doc.setTextColor(...COLORS.text);
  for (let index = 0; index < leftColumn.length; index += 1) {
    y = ensureSpace(doc, y, sdgLineHeight + 2, margin);
    const leftNum = leftColumn[index];
    const rightNum = rightColumn[index];
    const leftChecked = selectedSdgs.has(leftNum) ? '[X]' : '[ ]';
    const rightChecked = selectedSdgs.has(rightNum) ? '[X]' : '[ ]';
    doc.text(`${leftChecked} ${leftNum}. ${SDG_LABELS[leftNum]}`, margin + 2, y);
    doc.text(`${rightChecked} ${rightNum}. ${SDG_LABELS[rightNum]}`, margin + colWidth + 8, y);
    y += sdgLineHeight;
  }

  y += 6;
  y = drawFieldRow(doc, 'Collaborating Organization', formData.collaboratingOrganization, y, margin, maxWidth);
  y = drawMultilineBlock(doc, 'Sponsorship Information', formData.sponsorshipInfo, y, margin, maxWidth);

  y += SECTION_GAP;
  y = drawSectionTitle(doc, 'I. ATTACHMENTS', y, margin, maxWidth);
  y = drawFieldRow(doc, 'Programme Poster', formData.posterPreview ? 'Attached' : '—', y, margin, maxWidth);
  y = drawFieldRow(
    doc,
    'Proposal Paper',
    formData.proposalPaperName || formData.proposalPaperPreview ? 'Attached' : '—',
    y,
    margin,
    maxWidth
  );
  y = drawFieldRow(
    doc,
    'Sponsor Letter',
    formData.sponsorLetterName || formData.sponsorLetterPreview ? 'Attached' : '—',
    y,
    margin,
    maxWidth
  );
  y = drawFieldRow(
    doc,
    'Risk Assessment',
    formData.riskAssessmentName || formData.riskAssessmentPreview ? 'Attached' : '—',
    y,
    margin,
    maxWidth
  );
  y = drawFieldRow(
    doc,
    'Supporting Documents',
    formData.supportingDocumentCount != null ? `${formData.supportingDocumentCount} file(s)` : 'See CampusLink+ upload step',
    y,
    margin,
    maxWidth
  );

  y += SECTION_GAP;
  y = ensureSpace(doc, y, 85, margin);
  y = drawSectionTitle(doc, 'J. KELULUSAN PENASIHAT KELAB', y, margin, maxWidth);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.text);
  doc.text(
    'Dokumen ini mesti ditandatangani oleh Penasihat Kelab sebelum dihantar untuk semakan MPP dan HEPA.',
    margin,
    y,
    { maxWidth }
  );
  y += 10;
  y = drawFieldRow(doc, 'Nama Penasihat', formData.advisor?.advisorName, y, margin, maxWidth);
  y = drawFieldRow(doc, 'E-mel Penasihat', formData.advisor?.advisorEmail, y, margin, maxWidth);
  y += 6;

  const signatureHeight = 32;
  y = ensureSpace(doc, y, signatureHeight + 20, margin);
  doc.setDrawColor(...COLORS.border);
  doc.rect(margin, y, maxWidth, signatureHeight);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.muted);
  doc.text('Tandatangan Penasihat', margin + 3, y + 6);

  const dateBoxWidth = 42;
  doc.text('Tarikh', margin + maxWidth - dateBoxWidth + 2, y + 6);
  doc.rect(margin + maxWidth - dateBoxWidth, y + 10, dateBoxWidth - 4, 10);
  y += signatureHeight + 8;

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.text(
    'Muat naik salinan PDF yang telah ditandatangani di langkah terakhir borang CampusLink+ sebelum penghantaran kepada MPP.',
    margin,
    y,
    { maxWidth }
  );

  const totalPages = doc.internal.getNumberOfPages();
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    drawPageFooter(doc, margin);
  }

  const fileName = buildProgrammeFormFileName(formData.title);
  const documentTitle = fileName.replace(/\.pdf$/i, '');
  doc.setProperties({
    title: documentTitle,
    subject: formData.title || 'Programme Proposal',
    creator: 'CampusLink+',
  });

  if (options.download) {
    doc.save(fileName);
  }

  return { blob: doc.output('blob'), fileName, documentTitle };
};

export default generateProgrammeFormPdf;
