import {
  REPORT_COLORS,
  REPORT_SUBTITLE,
  formatReportDateTime,
  getReportTitle,
} from './reportPdfTheme';

const FOOTER_RESERVE = 22;

function setFill(doc, rgb) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}

function setDraw(doc, rgb) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}

function setText(doc, rgb) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

export function drawReportPageFooter(doc, margin, generatedOn) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const page = doc.internal.getCurrentPageInfo().pageNumber;
  const total = doc.internal.getNumberOfPages();
  const y = pageHeight - 14;

  setDraw(doc, REPORT_COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(margin, y - 6, pageWidth - margin, y - 6);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  setText(doc, REPORT_COLORS.primary);
  doc.text('CampusLink+', margin, y - 1);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  setText(doc, REPORT_COLORS.muted);
  doc.text(REPORT_SUBTITLE, margin, y + 3);

  doc.text(
    'This document is system-generated. No signature is required.',
    pageWidth / 2,
    y,
    { align: 'center' }
  );

  doc.text(`Generated on ${generatedOn}`, pageWidth - margin, y - 1, { align: 'right' });
  doc.text(`Page ${page} of ${total}`, pageWidth - margin, y + 3, { align: 'right' });
}

export function stampReportFooters(doc, margin, generatedOn) {
  const total = doc.internal.getNumberOfPages();
  for (let page = 1; page <= total; page += 1) {
    doc.setPage(page);
    drawReportPageFooter(doc, margin, generatedOn);
  }
}

export function drawReportHeader(doc, margin, pageWidth, reportType) {
  let y = 14;

  setFill(doc, REPORT_COLORS.primary);
  doc.rect(pageWidth - margin - 18, y - 4, 18, 3, 'F');

  setDraw(doc, REPORT_COLORS.primary);
  doc.setLineWidth(0.9);
  doc.line(margin, y + 10, pageWidth - margin, y + 10);
  y += 18;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  setText(doc, REPORT_COLORS.primary);
  doc.text(getReportTitle(reportType), margin, y);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  setText(doc, REPORT_COLORS.primaryLight);
  doc.text(REPORT_SUBTITLE, margin, y);
  y += 8;

  setDraw(doc, REPORT_COLORS.border);
  doc.setLineWidth(0.35);
  doc.line(margin, y, pageWidth - margin, y);

  return y + 8;
}

function drawMetaField(doc, label, value, x, y, width) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  setText(doc, REPORT_COLORS.muted);
  doc.text(label, x, y);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  setText(doc, REPORT_COLORS.text);
  const lines = doc.splitTextToSize(String(value || '—'), width - 2);
  doc.text(lines[0] || '—', x, y + 4.5);
  return y + (lines.length > 1 ? 9 : 8);
}

export function drawReportMetaGrid(doc, margin, pageWidth, meta, startY) {
  const colWidth = (pageWidth - margin * 2 - 8) / 2;
  const leftX = margin;
  const rightX = margin + colWidth + 8;
  let leftY = startY;
  let rightY = startY;

  const leftFields = [
    ['Programme', meta.programmeTitle],
    ['Organized By', meta.organizerClub],
    ['Venue', meta.venue],
    ['Programme Date', meta.programmeDate],
  ];
  const rightFields = [
    ['Reference No.', meta.reportId],
    ['Generated On', meta.generatedOn],
    ['Generated By', meta.generatedBy],
    ['Report Type', meta.reportTypeLabel],
  ];

  leftFields.forEach(([label, value]) => {
    leftY = drawMetaField(doc, label, value, leftX, leftY, colWidth);
  });
  rightFields.forEach(([label, value]) => {
    rightY = drawMetaField(doc, label, value, rightX, rightY, colWidth);
  });

  return Math.max(leftY, rightY) + 4;
}

export function drawSummaryBox(doc, margin, pageWidth, summaryLines, startY) {
  if (!summaryLines?.length) return startY;

  const boxHeight = 8 + summaryLines.length * 5.5;
  setFill(doc, REPORT_COLORS.rowAlt);
  setDraw(doc, REPORT_COLORS.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, startY, pageWidth - margin * 2, boxHeight, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  setText(doc, REPORT_COLORS.primary);
  doc.text('SUMMARY', margin + 4, startY + 5.5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  setText(doc, REPORT_COLORS.text);
  summaryLines.forEach((line, index) => {
    doc.text(line, margin + 4, startY + 11 + index * 5.5);
  });

  return startY + boxHeight + 8;
}

function getStatusStyle(statusText) {
  const status = String(statusText || '').toUpperCase();
  if (['ACTIVE', 'PRESENT', 'COMPLETED', 'APPROVED', 'ATTENDED'].includes(status)) {
    return { bg: REPORT_COLORS.successBg, text: REPORT_COLORS.successText, label: formatStatusLabel(status) };
  }
  if (status.includes('PENDING')) {
    return { bg: REPORT_COLORS.warningBg, text: REPORT_COLORS.warningText, label: formatStatusLabel(status) };
  }
  return { bg: REPORT_COLORS.neutralBg, text: REPORT_COLORS.neutralText, label: formatStatusLabel(status) };
}

function formatStatusLabel(status) {
  if (!status) return '—';
  return status
    .toLowerCase()
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function getColumnWeight(header) {
  const h = String(header).toLowerCase();
  if (h === 'no.' || h === 'no') return 0.055;
  if (h.includes('name')) return 0.2;
  if (h.includes('matric')) return 0.11;
  if (h.includes('faculty')) return 0.17;
  if (h.includes('reg.') && h.includes('status')) return 0.14;
  if (h.includes('merit') || h.includes('pts')) return 0.09;
  if (h.includes('registered') || h.includes('checked')) return 0.15;
  if (h.includes('session')) return 0.11;
  return 0.12;
}

function computeColumnWidths(headers, usableWidth) {
  const tableHeaders = ['No.', ...headers];
  const weights = tableHeaders.map(getColumnWeight);
  const totalWeight = weights.reduce((sum, w) => sum + w, 0);
  return weights.map((weight) => (weight / totalWeight) * usableWidth);
}

function isStatusColumn(header) {
  return String(header).toLowerCase().includes('status');
}

function drawWrappedHeaderText(doc, text, x, y, maxWidth) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.8);
  const lines = doc.splitTextToSize(String(text).toUpperCase(), maxWidth - 3).slice(0, 2);
  lines.forEach((line, index) => {
    doc.text(line, x, y + 4 + index * 3.2);
  });
  return lines.length;
}

function drawStatusBadge(doc, x, y, statusText, maxWidth) {
  const style = getStatusStyle(statusText);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  const textWidth = doc.getTextWidth(style.label);
  const badgeWidth = Math.min(maxWidth - 2, Math.max(textWidth + 8, 16));
  const badgeHeight = 5;

  setFill(doc, style.bg);
  if (doc.roundedRect) {
    doc.roundedRect(x, y - 3.8, badgeWidth, badgeHeight, 1.2, 1.2, 'F');
  } else {
    doc.rect(x, y - 3.8, badgeWidth, badgeHeight, 'F');
  }

  setText(doc, style.text);
  doc.text(style.label, x + 2.5, y);
}

function measureRowHeight(doc, row, headers, colWidths, baseRowHeight) {
  let maxLines = 1;
  row.forEach((value, index) => {
    if (isStatusColumn(headers[index])) return;
    const lines = doc.splitTextToSize(String(value ?? '—'), colWidths[index] - 4);
    maxLines = Math.max(maxLines, lines.length);
  });
  return Math.max(baseRowHeight, maxLines * 3.4 + 2);
}

export function drawReportTable({
  doc,
  margin,
  pageWidth,
  headers,
  rows,
  startY,
  landscape,
}) {
  const usableWidth = pageWidth - margin * 2;
  const tableHeaders = ['No.', ...headers];
  const colWidths = computeColumnWidths(headers, usableWidth);
  const headerLineCount = tableHeaders.reduce((max, header, index) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.8);
    const lines = doc.splitTextToSize(String(header).toUpperCase(), colWidths[index] - 3);
    return Math.max(max, Math.min(lines.length, 2));
  }, 1);
  const headerHeight = 5 + headerLineCount * 3.2;
  const baseRowHeight = 6;
  let y = startY;

  const drawTableHeader = () => {
    setFill(doc, REPORT_COLORS.primary);
    doc.rect(margin, y, usableWidth, headerHeight, 'F');

    setText(doc, REPORT_COLORS.white);
    let x = margin;
    tableHeaders.forEach((header, index) => {
      drawWrappedHeaderText(doc, header, x + 2, y, colWidths[index]);
      x += colWidths[index];
    });
    y += headerHeight;
  };

  const ensureSpace = (needed) => {
    const pageHeight = doc.internal.pageSize.getHeight();
    if (y + needed > pageHeight - FOOTER_RESERVE) {
      doc.addPage(landscape ? 'landscape' : 'portrait');
      y = 18;
      drawTableHeader();
    }
  };

  drawTableHeader();

  rows.forEach((row, rowIndex) => {
    const rowHeight = measureRowHeight(doc, row, headers, colWidths.slice(1), baseRowHeight);

    ensureSpace(rowHeight);

    if (rowIndex % 2 === 0) {
      setFill(doc, REPORT_COLORS.rowAlt);
      doc.rect(margin, y, usableWidth, rowHeight, 'F');
    }

    setDraw(doc, REPORT_COLORS.border);
    doc.setLineWidth(0.15);
    doc.line(margin, y + rowHeight, margin + usableWidth, y + rowHeight);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    setText(doc, REPORT_COLORS.text);
    doc.text(String(rowIndex + 1), margin + 2, y + 4.2);

    let x = margin + colWidths[0];
    row.forEach((value, index) => {
      const header = headers[index];
      const width = colWidths[index + 1];
      const cellX = x + 2;

      if (isStatusColumn(header)) {
        drawStatusBadge(doc, cellX, y + 4.2, value, width);
        x += width;
        return;
      }

      doc.setFont('helvetica', index === 0 ? 'bold' : 'normal');
      doc.setFontSize(7.5);
      setText(doc, REPORT_COLORS.text);
      const lines = doc.splitTextToSize(String(value ?? '—'), width - 4);
      doc.text(lines[0] || '—', cellX, y + 4.2);
      x += width;
    });

    y += rowHeight;
  });

  return y + 4;
}

export function buildReportMeta({
  programmeTitle,
  organizerClub,
  reportType,
  venue,
  programmeDate,
  generatedBy,
  reportId,
}) {
  const generatedOn = formatReportDateTime(new Date());
  return {
    programmeTitle: programmeTitle || '—',
    organizerClub: organizerClub || '—',
    venue: venue || '—',
    programmeDate: programmeDate || '—',
    reportId: reportId || '—',
    generatedOn,
    generatedBy: generatedBy || 'CampusLink+ System',
    reportTypeLabel: reportType || '—',
  };
}
